[theme]
primaryColor = "#3B2F9E"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#061B31"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
